# Generated by Django 4.0.3 on 2022-03-31 08:26

from django.db import migrations, models
import s3direct.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('date_published', models.DateTimeField(auto_now_add=True)),
                ('price', models.IntegerField()),
                ('description', models.TextField()),
                ('image', s3direct.fields.S3DirectField()),
            ],
        ),
    ]
